spring.application.name=CutDemoTwo
server.port=8080

# PackingSolver C++ 可执行文件路径
packingsolver.executable.path=d:/GitLab/packingsolver/build/src/rectangleguillotine/packingsolver_rectangleguillotine.exe

spring.jackson.deserialization.fail-on-null-for-primitives=false
